spring.application.name=Spring Estudo Alura

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/estudoalura
spring.datasource.username=root
spring.datasource.password=${BD_SECRET:bancodedados}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html


# ${VARIAVEL_AMBIENTE:valor_default}
springestudoalura.token.jwt.secret-key=${JWT_SECRET:123456789}

#Comados para modificar o nome dos parâmetros das urls paginadas
#spring.data.web.pageable.page-parameter=pagina
#spring.data.web.pageable.size-parameter=tamanho
#spring.data.web.sort.sort-parameter=ordem
