INSERT INTO
    medicos (
        crm,
        email,
        bairro,
        cep,
        cidade,
        complemento,
        logradouro,
        numero,
        uf,
        especialidade,
        nome,
        telefone
    )
VALUES
    (
        'CRM/UF 482391',
        'ana.souza@estudo.spring',
        'Bela Vista',
        '01311-000',
        'São Paulo',
        'Sala 1203',
        'Avenida Paulista',
        '1578',
        'SP',
        'CARDIOLOGIA',
        'Ana Beatriz de Albuquerque Souza',
        '11 77834-5612'
    ),
    (
        'CRM/UF 593021',
        'joaop@estudo.spring',
        'Copacabana',
        '22010-000',
        'Rio de Janeiro',
        'Bloco B',
        'Avenida Atlântica',
        '1702',
        'RJ',
        'ORTOPEDIA',
        'João Pereira',
        '21 76745-2391'
    ),
    (
        'CRM/UF 774512',
        'mariana.ribeiro@estudo.spring',
        'Consolação',
        '01302-000',
        'São Paulo',
        'Conjunto 45',
        'Rua da Consolação',
        '900',
        'SP',
        'DERMATOLOGIA',
        'Mariana Coutinho Ribeiro',
        '11 76572-8834'
    ),
    (
        'CRM/UF 318904',
        'carlos.lima@estudo.spring',
        'Jardim Botânico',
        '22470-050',
        'Rio de Janeiro',
        'Sala 302',
        'Rua Jardim Botânico',
        '414',
        'RJ',
        'GINECOLOGIA',
        'Carlos Eduardo Lima',
        '21 77681-4502'
    ),
    (
        'CRM/UF 660193',
        'luiza@estudo.spring',
        'Sé',
        '01001-000',
        'São Paulo',
        '1º Andar',
        'Praça da Sé',
        '100',
        'SP',
        'ORTOPEDIA',
        'Luiza Martins',
        '11 77123-4409'
    ),
    (
        'CRM/UF 902145',
        'fernando.almeida@estudo.spring',
        'Centro',
        '20040-002',
        'Rio de Janeiro',
        'Sala 808',
        'Avenida Rio Branco',
        '156',
        'RJ',
        'CARDIOLOGIA',
        'Fernando Henrique Tavares Almeida',
        '21 76890-7741'
    ),
    (
        'CRM/UF 845219',
        'patricia.silva@estudo.spring',
        'Itaim Bibi',
        '04538-132',
        'São Paulo',
        'Sala 1502',
        'Avenida Brigadeiro Faria Lima',
        '2232',
        'SP',
        'GINECOLOGIA',
        'Patrícia Gomes da Silva',
        '11 77456-9981'
    ),
    (
        'CRM/UF 731284',
        'rafaelm@estudo.spring',
        'Ipanema',
        '22410-003',
        'Rio de Janeiro',
        'Cobertura',
        'Rua Visconde de Pirajá',
        '550',
        'RJ',
        'DERMATOLOGIA',
        'Rafael Mendes',
        '21 77901-6633'
    ),
    (
        'CRM/UF 519203',
        'camila.nogueira@estudo.spring',
        'Moema',
        '04029-200',
        'São Paulo',
        'Sala 607',
        'Avenida Ibirapuera',
        '3103',
        'SP',
        'CARDIOLOGIA',
        'Camila Andrade Nogueira',
        '11 76812-3377'
    ),
    (
        'CRM/UF 662780',
        'thiago@estudo.spring',
        'Centro',
        '20071-004',
        'Rio de Janeiro',
        'Sala 1401',
        'Avenida Presidente Vargas',
        '509',
        'RJ',
        'ORTOPEDIA',
        'Thiago Oliveira',
        '21 76544-1128'
    ),
    (
        'CRM/UF 993412',
        'juliana.castro@estudo.spring',
        'Jardins',
        '01426-001',
        'São Paulo',
        'Sala 210',
        'Rua Oscar Freire',
        '379',
        'SP',
        'DERMATOLOGIA',
        'Juliana Ferreira Castro',
        '11 77765-2219'
    ),
    (
        'CRM/UF 410275',
        'bruno.menezes@estudo.spring',
        'Centro',
        '20050-020',
        'Rio de Janeiro',
        'Sala 502',
        'Largo da Carioca',
        '12',
        'RJ',
        'GINECOLOGIA',
        'Bruno Carvalho de Menezes Filho',
        '21 77033-8894'
    ),
    (
        'CRM/UF 128774',
        'isabela.rocha@estudo.spring',
        'República',
        '01035-000',
        'São Paulo',
        'Sala 1104',
        'Avenida São João',
        '439',
        'SP',
        'ORTOPEDIA',
        'Isabela Rocha',
        '11 76988-4410'
    ),
    (
        'CRM/UF 874320',
        'eduardol@estudo.spring',
        'Botafogo',
        '22250-040',
        'Rio de Janeiro',
        'Sala 909',
        'Praia de Botafogo',
        '300',
        'RJ',
        'CARDIOLOGIA',
        'Eduardo Lima',
        '21 77321-5540'
    ),
    (
        'CRM/UF 556902',
        'renata.albuquerque@estudo.spring',
        'Pinheiros',
        '05402-000',
        'São Paulo',
        'Sala 404',
        'Avenida Rebouças',
        '1357',
        'SP',
        'GINECOLOGIA',
        'Renata Vasconcelos Albuquerque',
        '11 77200-6638'
    ),
    (
        'CRM/UF 302198',
        'leonardo@estudo.spring',
        'Leblon',
        '22431-050',
        'Rio de Janeiro',
        'Sala 1001',
        'Rua Dias Ferreira',
        '45',
        'RJ',
        'DERMATOLOGIA',
        'Leonardo Souza',
        '21 77888-1203'
    ),
    (
        'CRM/UF 741258',
        'natalia.santos@estudo.spring',
        'Vila Olímpia',
        '04506-001',
        'São Paulo',
        'Sala 808',
        'Avenida Santo Amaro',
        '2222',
        'SP',
        'CARDIOLOGIA',
        'Natália Cristina Pereira dos Santos',
        '11 77345-7782'
    ),
    (
        'CRM/UF 665431',
        'felipe.andrade@estudo.spring',
        'Lagoa',
        '22470-003',
        'Rio de Janeiro',
        'Sala 303',
        'Avenida Borges de Medeiros',
        '997',
        'RJ',
        'ORTOPEDIA',
        'Felipe Andrade',
        '21 76661-9907'
    ),
    (
        'CRM/UF 880144',
        'vanessa.prado@estudo.spring',
        'Centro',
        '01021-000',
        'São Paulo',
        'Sala 601',
        'Rua 25 de Março',
        '785',
        'SP',
        'DERMATOLOGIA',
        'Vanessa Oliveira Prado',
        '11 77654-3321'
    ),
    (
        'CRM/UF 954877',
        'marcelo.costa@estudo.spring',
        'Centro',
        '20010-000',
        'Rio de Janeiro',
        'Sala 707',
        'Rua Primeiro de Março',
        '23',
        'RJ',
        'GINECOLOGIA',
        'Marcelo Augusto Ribeiro da Costa',
        '21 77119-4456'
    );
    