INSERT INTO
    usuarios (
        login,
        senha
    )
VALUES
    (
        'marcos.almeida@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'ana.costa.silva@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'lucas.pereira@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'fernanda.melo@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'rafael.andrade@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'juliana.santos@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'bruno.alves@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'patricia.rodrigues@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'thiago.cavalcanti@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'camila.freitas@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'eduardo.martins@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'larissa.monteiro@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'felipe.gomes@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'renata.silveira@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'marcelo.ferraz@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'isabela.duarte@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'gustavo.nogueira@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'aline.barros@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'rodrigo.teixeira@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    ),
    (
        'carolina.lopes@teste.spring',
        '$2a$10$q9xUw9JIJpO2aDJCHPfcFuVH2HsRBqCfOLaTa9vzF.2DvZsnBtXKS'
    );
